### ISSUE TITLE
Build error on qt5

### ISSUE THREAD

**Issue by neochapay** [cybercatalyst/jackcontrol#5]
When i build on qt5.5.1 i have error:

```
/home/neochapay/workspace/jackcontrol/jackcontrol/jackscopewidget.cpp:237: error: 'class QtJack::Client' has no member named 'unregisterPort'
             _client.unregisterPort(probe->_port);
                     ^
```
